# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LayerQuery
                                 A QGIS plugin
 Plugin to query layers
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-05-31
        copyright            : (C) 2018 by John Wolynec
        email                : johnw@barnesduncan.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LayerQuery class from file LayerQuery.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .layer_query import LayerQuery
    return LayerQuery(iface)
